
//----------------------------------------------------
// The following code was generated by CUP v0.10i
// Fri Jun 04 15:43:23 EDT 1999
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int QUESTION = 34;
  public static final int EOF = 0;
  public static final int PAPER = 19;
  public static final int LINE = 24;
  public static final int LBRACKET = 13;
  public static final int ERROR = 6;
  public static final int DIVIDE = 5;
  public static final int FIELD = 31;
  public static final int NUMBER = 26;
  public static final int error = 1;
  public static final int VALUE = 28;
  public static final int PAUSE = 30;
  public static final int UMINUS = 7;
  public static final int MINUS = 3;
  public static final int COMMAND = 25;
  public static final int COMMANDNAME = 35;
  public static final int TIMES = 4;
  public static final int LPAREN = 8;
  public static final int RPAREN = 9;
  public static final int ALIAS = 10;
  public static final int INTEGER = 32;
  public static final int LOAD = 29;
  public static final int PEN = 20;
  public static final int ESCAPE = 27;
  public static final int ANTIALIAS = 11;
  public static final int LBRACE = 15;
  public static final int PLUS = 2;
  public static final int RBRACE = 14;
  public static final int FOREVER = 23;
  public static final int RETURN = 21;
  public static final int SET = 18;
  public static final int RBRACKET = 12;
  public static final int NAME = 33;
  public static final int REPEAT = 22;
  public static final int LBLOCK = 17;
  public static final int RBLOCK = 16;
}

